parameters:
    locale: en

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    App\Api\DeckApiInterface:
        class: App\Tests\Api\TestApi
